### ISSUE TITLE
Configure defaults via properties file

### ISSUE THREAD

**Issue by jackmatt2** [origin-energy/java-snapshot-testing#62]
Currently users require adding an `@SnapshotConfig` to every class where the defaults don't suite their needs.  Instead this should be managed by a properties file as it will be much more convenient.

```
snapshot-config.yaml
```

```
default:
  test-src-dir: src/test/kotlin
  snapshot-serializer: au.com.origin.snapshots.serializers.ToStringSnapshotSerializer.class
  reporters: 
    - au.com.origin.snapshots.reporters.PlainTextSnapshotReporter.class
  comparator: au.com.origin.snapshots.comparators.PlainTextEqualsComparator.class
```
